name: allCov
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  odbTest:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 1-testDb
          MYSQL_DATABASE: heratestdb
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Manual go1.20
      run: wget -nv https://go.dev/dl/go1.20.7.linux-amd64.tar.gz
    - run: sed -e 's,http.*/,,' SHA256 | sha256sum -c
    - run: tar zxf go1.20.7.linux-amd64.tar.gz
    - name: End - Manual go1.20
      run: /home/runner/work/hera2flow/hera2flow/go/bin/go version

    - name: allCovSh
      run: tests/unittest/allcover.sh
