name: gvenzl oracle
on:
  workflow_dispatch:
jobs:
  odbTest:
    runs-on: ubuntu-latest

    services:
      odb3:
        image: gvenzl/oracle-xe:21-slim-faststart
        env:
          ORACLE_PASSWORD: 1.2.8MomOfferExpand 
        ports:
          - 1521:1521
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15
    - name: System Test
      run: tests/oracle.sh
